### ISSUE TITLE
Pull Request #8 でコンパイルエラー

### ISSUE THREAD

**Issue by shoshoi** [shoshoi/VRoidAvatarSetupUtils#12]
@yokra9 
先日はPull Requestありがとうございました。
Pull Request #8 をマージしたところエラーが出たので、内容の確認をお願いします。

下記コードで`gameObject.transform`が参照エラーになり、コンパイルエラーとなります。
https://github.com/shoshoi/VRoidAvatarSetupUtils/blob/22c4b6739f491247d4854b615ed6c1de310cb473/Editor/VRoidAvatar.cs#L510

この変更はPull Request #8 の変更です。変更前は`targetObject.transform`を参照していました。
`gameObject.transform`と`targetObject.transform`どちらが正しいか確認をお願いします。

**Comment by yokra9** [comment]
お手数をおかけしてすみません、fork(kai)で行った修正をそのまま移植したため発生したバグのようです。確認して対処します。今後はこちらのレポジトリにPRを送る形で改善に参加させてもらえればと思いますので、このような失敗は減らせると思います。

**Comment by shoshoi** [comment]
確認ありがとうございます。了解しました！対処よろしくお願いします。

**Comment by yokra9** [comment]
[v1.0.1](https://github.com/shoshoi/VRoidAvatarSetupUtils/releases/tag/v1.0.1) リリースに向けた一連の改修の中で、`CopyToTarget()` の引数が `targetObject` に変更されている点を見落としていました：

https://github.com/shoshoi/VRoidAvatarSetupUtils/blob/a91608958497a1848f599b27f0c2f42674890166/Editor/VRoidAvatar.cs#L110

https://github.com/shoshoi/VRoidAvatarSetupUtils/blob/0c6895a09bb85e06fbaeda32052df2dba62ce988/Editor/VRoidAvatar.cs#L141

従って、`targetObject.transform` が正しいです。#13 でPRを作成しましたので、ご確認お願いします。

---

動かないコードを push しておいて何なのですが、せっかくテストコードがありますので、GitHub Actions で自動テストを走らせたほうが便利かもしれません。
https://github.com/marketplace/actions/unity-test-runner

[GitHub Actions はしばしば利用しております](https://qiita.com/yokra9/items/fff4f2d141d5ebe88bd3)ので、もし困ったことがあれば協力させてください。

**Comment by shoshoi** [comment]
修正ありがとうございました。マージしました。
GitHub Actionsについて教えて頂きありがとうございます！試してみますね。
本issueは一旦クローズします。
